# TCL File Generated by Component Editor 17.0
# Sat Mar 03 15:56:54 MST 2018
# DO NOT MODIFY


# 
# L298N_Pwm "L298N Pwm" v1.0
# Jess & Kelly 2018.03.03.15:56:54
# PWM to work in conjunction with an L298N HBridge
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module L298N_Pwm
# 
set_module_property DESCRIPTION "PWM to work in conjunction with an L298N HBridge"
set_module_property NAME L298N_Pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Jess & Kelly"
set_module_property DISPLAY_NAME "L298N Pwm"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL L298N_Pwm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file L298N_Pwm.vhd VHDL PATH L298N_Pwm.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end a a Output 1
add_interface_port conduit_end b b Output 1
add_interface_port conduit_end a_comp a_comp Output 1
add_interface_port conduit_end b_comp b_comp Output 1
add_interface_port conduit_end en_a en_a Output 1
add_interface_port conduit_end en_b en_b Output 1


# 
# connection point step
# 
add_interface step avalon end
set_interface_property step addressUnits WORDS
set_interface_property step associatedClock clock
set_interface_property step associatedReset reset
set_interface_property step bitsPerSymbol 8
set_interface_property step burstOnBurstBoundariesOnly false
set_interface_property step burstcountUnits WORDS
set_interface_property step explicitAddressSpan 0
set_interface_property step holdTime 0
set_interface_property step linewrapBursts false
set_interface_property step maximumPendingReadTransactions 0
set_interface_property step maximumPendingWriteTransactions 0
set_interface_property step readLatency 0
set_interface_property step readWaitTime 1
set_interface_property step setupTime 0
set_interface_property step timingUnits Cycles
set_interface_property step writeWaitTime 0
set_interface_property step ENABLED true
set_interface_property step EXPORT_OF ""
set_interface_property step PORT_NAME_MAP ""
set_interface_property step CMSIS_SVD_VARIABLES ""
set_interface_property step SVD_ADDRESS_GROUP ""

add_interface_port step step_write_n write_n Input 1
add_interface_port step step_writedata writedata Input 16
add_interface_port step step_read_n read_n Input 1
add_interface_port step step_readdata readdata Output 16
set_interface_assignment step embeddedsw.configuration.isFlash 0
set_interface_assignment step embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment step embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment step embeddedsw.configuration.isPrintableDevice 0


# 
# connection point cycle
# 
add_interface cycle avalon end
set_interface_property cycle addressUnits WORDS
set_interface_property cycle associatedClock clock
set_interface_property cycle associatedReset reset
set_interface_property cycle bitsPerSymbol 8
set_interface_property cycle burstOnBurstBoundariesOnly false
set_interface_property cycle burstcountUnits WORDS
set_interface_property cycle explicitAddressSpan 0
set_interface_property cycle holdTime 0
set_interface_property cycle linewrapBursts false
set_interface_property cycle maximumPendingReadTransactions 0
set_interface_property cycle maximumPendingWriteTransactions 0
set_interface_property cycle readLatency 0
set_interface_property cycle readWaitTime 1
set_interface_property cycle setupTime 0
set_interface_property cycle timingUnits Cycles
set_interface_property cycle writeWaitTime 0
set_interface_property cycle ENABLED true
set_interface_property cycle EXPORT_OF ""
set_interface_property cycle PORT_NAME_MAP ""
set_interface_property cycle CMSIS_SVD_VARIABLES ""
set_interface_property cycle SVD_ADDRESS_GROUP ""

add_interface_port cycle cycle_write_n write_n Input 1
add_interface_port cycle cycle_writedata writedata Input 32
add_interface_port cycle cycle_readdata readdata Output 32
add_interface_port cycle cycle_read_n read_n Input 1
set_interface_assignment cycle embeddedsw.configuration.isFlash 0
set_interface_assignment cycle embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cycle embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cycle embeddedsw.configuration.isPrintableDevice 0


# 
# connection point duty
# 
add_interface duty avalon end
set_interface_property duty addressUnits WORDS
set_interface_property duty associatedClock clock
set_interface_property duty associatedReset reset
set_interface_property duty bitsPerSymbol 8
set_interface_property duty burstOnBurstBoundariesOnly false
set_interface_property duty burstcountUnits WORDS
set_interface_property duty explicitAddressSpan 0
set_interface_property duty holdTime 0
set_interface_property duty linewrapBursts false
set_interface_property duty maximumPendingReadTransactions 0
set_interface_property duty maximumPendingWriteTransactions 0
set_interface_property duty readLatency 0
set_interface_property duty readWaitTime 1
set_interface_property duty setupTime 0
set_interface_property duty timingUnits Cycles
set_interface_property duty writeWaitTime 0
set_interface_property duty ENABLED true
set_interface_property duty EXPORT_OF ""
set_interface_property duty PORT_NAME_MAP ""
set_interface_property duty CMSIS_SVD_VARIABLES ""
set_interface_property duty SVD_ADDRESS_GROUP ""

add_interface_port duty duty_write_n write_n Input 1
add_interface_port duty duty_writedata writedata Input 32
add_interface_port duty duty_read_n read_n Input 1
add_interface_port duty duty_readdata readdata Output 32
set_interface_assignment duty embeddedsw.configuration.isFlash 0
set_interface_assignment duty embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment duty embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment duty embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dir
# 
add_interface dir avalon end
set_interface_property dir addressUnits WORDS
set_interface_property dir associatedClock clock
set_interface_property dir associatedReset reset
set_interface_property dir bitsPerSymbol 8
set_interface_property dir burstOnBurstBoundariesOnly false
set_interface_property dir burstcountUnits WORDS
set_interface_property dir explicitAddressSpan 0
set_interface_property dir holdTime 0
set_interface_property dir linewrapBursts false
set_interface_property dir maximumPendingReadTransactions 0
set_interface_property dir maximumPendingWriteTransactions 0
set_interface_property dir readLatency 0
set_interface_property dir readWaitTime 1
set_interface_property dir setupTime 0
set_interface_property dir timingUnits Cycles
set_interface_property dir writeWaitTime 0
set_interface_property dir ENABLED true
set_interface_property dir EXPORT_OF ""
set_interface_property dir PORT_NAME_MAP ""
set_interface_property dir CMSIS_SVD_VARIABLES ""
set_interface_property dir SVD_ADDRESS_GROUP ""

add_interface_port dir dir_write_n write_n Input 1
add_interface_port dir dir_writedata writedata Input 8
add_interface_port dir dir_read_n read_n Input 1
add_interface_port dir dir_readdata readdata Output 8
set_interface_assignment dir embeddedsw.configuration.isFlash 0
set_interface_assignment dir embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment dir embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment dir embeddedsw.configuration.isPrintableDevice 0


# 
# connection point stepMode
# 
add_interface stepMode avalon end
set_interface_property stepMode addressUnits WORDS
set_interface_property stepMode associatedClock clock
set_interface_property stepMode associatedReset reset
set_interface_property stepMode bitsPerSymbol 8
set_interface_property stepMode burstOnBurstBoundariesOnly false
set_interface_property stepMode burstcountUnits WORDS
set_interface_property stepMode explicitAddressSpan 0
set_interface_property stepMode holdTime 0
set_interface_property stepMode linewrapBursts false
set_interface_property stepMode maximumPendingReadTransactions 0
set_interface_property stepMode maximumPendingWriteTransactions 0
set_interface_property stepMode readLatency 0
set_interface_property stepMode readWaitTime 1
set_interface_property stepMode setupTime 0
set_interface_property stepMode timingUnits Cycles
set_interface_property stepMode writeWaitTime 0
set_interface_property stepMode ENABLED true
set_interface_property stepMode EXPORT_OF ""
set_interface_property stepMode PORT_NAME_MAP ""
set_interface_property stepMode CMSIS_SVD_VARIABLES ""
set_interface_property stepMode SVD_ADDRESS_GROUP ""

add_interface_port stepMode stepMode_read_n read_n Input 1
add_interface_port stepMode stepMode_readdata readdata Output 8
add_interface_port stepMode stepMode_write_n write_n Input 1
add_interface_port stepMode stepMode_writedata writedata Input 8
set_interface_assignment stepMode embeddedsw.configuration.isFlash 0
set_interface_assignment stepMode embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment stepMode embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment stepMode embeddedsw.configuration.isPrintableDevice 0

